### ISSUE TITLE
Improving Releases, tags and handling of the VERSION file

### ISSUE THREAD

**Issue by zsliu98** [sudara/pamplejuce#44]
When I want to release a new version, I have to:
- update the VERSION file
- git add & commit
- git tag & git push --tags

If I create the VERSION file from git tags, I can save myself from the first step:
```yml
    - name: Get lastest tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      id: get-latest-tag
      with:
        fallback: 0.0.0

    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "${{steps.get-latest-tag.outputs.tag}}" > VERSION
        VERSION=$(cat VERSION)
# ......
```

However in this case I have to make sure that the tags are in the format "-.-.-" What do you think about this?

See [this workflow](https://github.com/ZL-Audio/ZLEComp/actions/runs/6025137757/workflow) as an example.
